//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoredProcedures {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StoredProcedures.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @studentBirthdate.
        /// </summary>
        internal static string birthDateProcedureParam {
            get {
                return ResourceManager.GetString("birthDateProcedureParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dbo.CreateStudent.
        /// </summary>
        internal static string createProcedure {
            get {
                return ResourceManager.GetString("createProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dbo.DeleteAllStudents.
        /// </summary>
        internal static string deleteAllProcedure {
            get {
                return ResourceManager.GetString("deleteAllProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dbo.DeleteStudent.
        /// </summary>
        internal static string deleteProcedure {
            get {
                return ResourceManager.GetString("deleteProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @id.
        /// </summary>
        internal static string idProcedureParam {
            get {
                return ResourceManager.GetString("idProcedureParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @studentName.
        /// </summary>
        internal static string nameProcedureParam {
            get {
                return ResourceManager.GetString("nameProcedureParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dbo.ReadStudents.
        /// </summary>
        internal static string readProcedure {
            get {
                return ResourceManager.GetString("readProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dbo.SelectStudentById.
        /// </summary>
        internal static string selectStudentByIdProcedure {
            get {
                return ResourceManager.GetString("selectStudentByIdProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server=localhost,1433;Database=Vueling;User Id=sa;Password=yourStrong(!)Password;.
        /// </summary>
        internal static string sqlConnection {
            get {
                return ResourceManager.GetString("sqlConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @studentSurname.
        /// </summary>
        internal static string surnameProcedureParam {
            get {
                return ResourceManager.GetString("surnameProcedureParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dbo.UpdateStudent.
        /// </summary>
        internal static string updateProcedure {
            get {
                return ResourceManager.GetString("updateProcedure", resourceCulture);
            }
        }
    }
}
